[default]
description = "Default permissions for the plugin"
permissions = [
    "allow-list-fabric-loaders",
    "allow-list-fabric-versions",
    "allow-list-forge-versions",
    "allow-list-forge-loaders",
    "allow-list-quilt-versions",
    "allow-list-quilt-loaders"
]
